jpask1392/jamiepask-devstore.myshopify.com-built:
  - source: .github/sync.yml
    dest: .github/sync.yml
  - source: .github/workflows/
    dest: .github/workflows/
  - source: shopify/
    dest: jamiepask-devstore.myshopify.com
    deleteOrphaned: true

# jpask1392/jamiepask-devstore.myshopify.com:
#   - source: /
#     dest: shopify/
#     deleteOrphaned: true